# Generated by Django 4.2.3 on 2023-12-07 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 22, 35, 59, 817972), verbose_name='Дата создания'),
        ),
    ]
