# Generated by Django 4.2.3 on 2023-12-09 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 7, 2, 13, 833979), verbose_name='Дата создания'),
        ),
    ]
